import test from 'node:test';
import assert from 'node:assert/strict';
import {createRosterLoader,parseRosterDto,decideAllowed,resolveAllowed,decideSessionAction,parseAllowedEmails,normalizeEmail} from '../src/lib/allowlist.ts';
const email='operator@bo01.invalid',env=new Set([email]);
const dto=(administered,emails=[])=>({administered,emails:emails.map((email,i)=>({email,person_id:i+1}))});
function fixture(bodies,timeoutMs=50){let calls=0;return {count:()=>calls,load:createRosterLoader({baseUrl:'http://synthetic.invalid',sharedSecret:'synthetic',ttlMs:300000,timeoutMs,fetchImpl:async(url,init)=>{assert.equal(init.cache,'no-store');const body=bodies[Math.min(calls++,bodies.length-1)];if(body instanceof Error)throw body;return new Response(JSON.stringify(body));}})}}
test('normalization and env parser',()=>{assert.equal(normalizeEmail(' A@B.C '),'a@b.c');assert.deepEqual([...parseAllowedEmails(' A@B.C , ,')],['a@b.c']);});
test('administered empty roster revokes env operator',async()=>{const f=fixture([dto(true)]);const d=await resolveAllowed(email,env,f.load);assert.equal(d.allowed,false);assert.equal(decideSessionAction(d),'revoke');});
test('roster-only member admitted',async()=>{assert.equal((await resolveAllowed(email,new Set(),fixture([dto(true,[email])]).load)).source,'roster');});
test('only explicit unadministered admits env; roster rows cannot grant in bootstrap',async()=>{assert.equal((await resolveAllowed(email,env,fixture([dto(false)]).load)).source,'env');assert.equal((await resolveAllowed(email,new Set(),fixture([dto(false,[email])]).load)).allowed,false);});
test('revocation is revalidated before TTL',async()=>{const f=fixture([dto(true,[email]),dto(true)]);assert.equal((await resolveAllowed(email,env,f.load)).allowed,true);assert.equal((await resolveAllowed(email,env,f.load)).allowed,false);assert.equal(f.count(),2);});
test('revocation then fetch error cannot readmit env or existing session',async()=>{const f=fixture([dto(true),Error('offline')]);for(let i=0;i<2;i++){const d=await resolveAllowed(email,env,f.load);assert.equal(d.allowed,false);assert.equal(decideSessionAction(d),'revoke');}});
for(const [name,body] of Object.entries({array:[],missing:{emails:[]},string:{administered:'false',emails:[]},null:null,rows:{administered:false,emails:[null]},email:{administered:false,emails:[{email:42,person_id:1}]},id:{administered:false,emails:[{email,person_id:'1'}]},blank:{administered:false,emails:[{email:' ',person_id:1}]}}))test(`malformed ${name} denies env`,async()=>{assert.equal(parseRosterDto(body),null);assert.equal((await resolveAllowed(email,env,fixture([body]).load)).allowed,false);});
test('first fetch failure denies env',async()=>{assert.equal((await resolveAllowed(email,env,fixture([Error('offline')]).load)).allowed,false);});
test('HTTP 500 and invalid JSON deny',async()=>{for(const res of [new Response('{}',{status:500}),new Response('{')]){const load=createRosterLoader({baseUrl:'http://synthetic.invalid',sharedSecret:'',ttlMs:1,timeoutMs:50,fetchImpl:async()=>res});assert.equal((await resolveAllowed(email,env,load)).allowed,false);}});
test('timeout denies existing session and next request retries',async()=>{let calls=0;const load=createRosterLoader({baseUrl:'http://synthetic.invalid',sharedSecret:'',ttlMs:1,timeoutMs:10,fetchImpl:async(u,{signal})=>{calls++;if(calls>1)return new Response(JSON.stringify(dto(true,[email])));return await new Promise((resolve,reject)=>{const keep=setTimeout(()=>reject(Error('test deadline')),100);signal.addEventListener('abort',()=>{clearTimeout(keep);reject(signal.reason)},{once:true});});}});assert.equal(decideSessionAction(await resolveAllowed(email,env,load)),'revoke');assert.equal((await resolveAllowed(email,env,load)).allowed,true);assert.equal(calls,2);});
test('in-flight coalescing retains no completed roster',async()=>{const f=fixture([dto(true,[email]),dto(true)]);await Promise.all([f.load(),f.load()]);assert.equal(f.count(),1);assert.equal((await resolveAllowed(email,env,f.load)).allowed,false);assert.equal(f.count(),2);});
test('explicit recovery is separate: only subsequent server false re-enables bootstrap',async()=>{const f=fixture([dto(true),Error('recovery unavailable'),dto(false)]);assert.equal((await resolveAllowed(email,env,f.load)).allowed,false);assert.equal((await resolveAllowed(email,env,f.load)).allowed,false);assert.equal((await resolveAllowed(email,env,f.load)).allowed,true);});
test('unknown state and throwing loader fail closed',async()=>{assert.equal(decideSessionAction(decideAllowed(email,env,null)),'revoke');assert.equal((await resolveAllowed(email,env,async()=>{throw Error('offline')})).allowed,false);});

test('obsolete Set input cannot turn into implicit bootstrap',()=>{assert.equal(decideAllowed(email,env,new Set()).allowed,false);});
