// Actual page handler/callback unit regressions, no mounted React/API claims.
import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {fileURLToPath,pathToFileURL} from 'node:url';
const require=createRequire(import.meta.url),ts=require(process.env.BO_UI_TYPESCRIPT||'typescript');
const source=process.env.BO_UI_SOURCE_DIR||path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../src');
const {BoApiError}=await import(pathToFileURL(path.join(process.env.BO_UI_LIB_SOURCE_DIR||source,'lib/bo.ts')));
import {buildBotDelta,rebaseBotDraft} from '../src/lib/bot-delta.ts';
const filename='app/bo/bots/[id]/page.tsx';
function extract(name,ctx){const sf=ts.createSourceFile(filename,fs.readFileSync(path.join(source,filename),'utf8'),ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let body;function visit(n){if(ts.isFunctionDeclaration(n)&&n.name?.text===name)body=n.getText(sf);if(ts.isVariableDeclaration(n)&&n.name.getText(sf)===name&&ts.isCallExpression(n.initializer))body=n.initializer.arguments[0].getText(sf);ts.forEachChild(n,visit)}visit(sf);assert(body,'missing real handler '+name);const js=ts.transpileModule('const fn='+body+';', {compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;return Function(...Object.keys(ctx),js+'return fn;')(...Object.values(ctx));}
function fixture({role='admin',dirty=true}={}){const local={name:'typed',description:'typed desc',contentJson:'{"steps":[{"id":"s4"}]}'};let remote={bot:{name:'remote',description:'remote desc',draft_version:5},draft:{content:{steps:[{id:'s1'}]}}};const calls=[];const ctx={buildBotDelta,rebaseBotDraft,editBase:{current:{name:'original',description:'original desc',content:{steps:[{id:'s1'},{id:'s2'},{id:'s3'}]}}},...local,id:'bot',currentBot:{current:'bot'},draftDirty:{current:dirty},editRevision:{current:1},editVersion:{current:2},conflicted:false,setConflicted:x=>ctx.conflicted=x,state:{kind:'data',role,detail:{bot:{draft_version:2}}},BoApiError,setBusy:()=>{},setNotice:x=>calls.push({notice:x}),setState:x=>ctx.state=x,setName:x=>{local.name=x;ctx.name=x},setDescription:x=>{local.description=x;ctx.description=x},setContentJson:x=>{local.contentJson=x;ctx.contentJson=x},getBoBot:async()=>remote,listBoRuns:async()=>({runs:[]}),getBoSettings:async()=>({role}),patchBoBot:async(id,body)=>{calls.push({write:body});throw new BoApiError(409,'version_conflict')},load:null};ctx.load=()=>extract('load',ctx)();return{ctx,local,calls,remote,setRemote:x=>remote=x,run:name=>extract(name,ctx)()};}
test('409 retains name/description/JSON and actual base while refreshing remote',async()=>{const f=fixture(),before=structuredClone(f.local);await f.run('saveDraft');assert.deepEqual(f.local,before);assert.equal(f.ctx.editVersion.current,2);assert.equal(f.ctx.state.detail.bot.draft_version,5);assert(f.calls.some(x=>x.notice?.kind==='warn'));assert.equal(f.ctx.conflicted,true);assert.equal(f.calls.filter(x=>x.write).length,1);});
test('ordinary refetch leaves edits and v-3 read base intact',async()=>{const f=fixture(),before=structuredClone(f.local);await f.run('load');assert.deepEqual(f.local,before);assert.equal(f.ctx.editVersion.current,2);assert.equal(f.ctx.state.detail.bot.draft_version,5);});
test('after refetch request still uses version actually read, not fresh remote',async()=>{const f=fixture();await f.run('load');await f.run('saveDraft');assert.equal(f.calls.find(x=>x.write).write.expected_version,2);});
test('conflict blocks automatic repeated write without clearing draft',async()=>{const f=fixture();await f.run('saveDraft');const before=structuredClone(f.local);await f.run('saveDraft');assert.equal(f.calls.filter(x=>x.write).length,1);assert.deepEqual(f.local,before);});
test('viewer performs no UI write and retains draft',async()=>{const f=fixture({role:'viewer'}),before=structuredClone(f.local);await f.run('saveDraft');assert.equal(f.calls.filter(x=>x.write).length,0);assert.deepEqual(f.local,before);assert(f.calls.some(x=>x.notice?.kind==='danger'));});
test('server403 does not clear draft or read version',async()=>{const f=fixture(),before=structuredClone(f.local);f.ctx.patchBoBot=async()=>{throw new BoApiError(403,'forbidden')};await f.run('saveDraft');assert.deepEqual(f.local,before);assert.equal(f.ctx.draftDirty.current,true);assert.equal(f.ctx.editVersion.current,2);});
test('clean load initializes editor from actual remote revision',async()=>{const f=fixture({dirty:false});await f.run('load');assert.equal(f.local.name,'remote');assert.equal(f.ctx.editVersion.current,5);});
test('successful save refreshes clean draft and base from readback',async()=>{const f=fixture();f.ctx.patchBoBot=async()=>({});await f.run('saveDraft');assert.equal(f.ctx.draftDirty.current,false);assert.equal(f.local.name,'remote');assert.equal(f.ctx.editVersion.current,5);});
test('new edit arriving while request resolves remains dirty and preserved',async()=>{const f=fixture();f.ctx.patchBoBot=async()=>{extract('editName',f.ctx)('newer unsent');return{}};await f.run('saveDraft');assert.equal(f.local.name,'newer unsent');assert.equal(f.ctx.draftDirty.current,true);assert.equal(f.ctx.editVersion.current,2);assert(f.calls.some(x=>x.notice?.text.includes('nu au fost încă salvate')));});
test('explicit discard alone may replace local draft and clear conflict',async()=>{const f=fixture();f.ctx.conflicted=true;await f.run('discardAndReload');assert.equal(f.local.name,'remote');assert.equal(f.ctx.editVersion.current,5);assert.equal(f.ctx.conflicted,false);});
test('failed refetch preserves local draft and base',async()=>{const f=fixture(),before=structuredClone(f.local);f.ctx.getBoBot=async()=>{throw Error('offline')};await f.run('load');assert.deepEqual(f.local,before);assert.equal(f.ctx.editVersion.current,2);assert.equal(f.ctx.state.kind,'data');});
test('late response for other bot cannot replace editor',async()=>{const f=fixture({dirty:false}),before=structuredClone(f.local);f.ctx.currentBot.current='other';await f.run('load');assert.deepEqual(f.local,before);});
test('explicit reload/rebase keeps draft operations and remote concurrent step',async()=>{const f=fixture();f.setRemote({bot:{name:'remote',description:'remote desc',draft_version:8},draft:{content:{steps:[{id:'s1'},{id:'s2'},{id:'s3'},{id:'s5'}]}}});await f.run('reloadPreservingDraft');assert.equal(f.local.name,'typed');assert.equal(f.ctx.editVersion.current,8);assert.deepEqual(JSON.parse(f.local.contentJson).steps,[{id:'s5'},{id:'s4'}]);assert.equal(f.ctx.conflicted,false);assert.equal(f.ctx.draftDirty.current,true);});
test('publish sends only version actually read and refuses stale409 without retry',async()=>{const f=fixture({dirty:false});let sent;f.ctx.publishBoBot=async(id,v)=>{sent={id,v};throw new BoApiError(409,'stale')};await f.run('publish');assert.deepEqual(sent,{id:'bot',v:2});assert(f.calls.some(x=>x.notice?.kind==='warn'));});
test('publish blocks unsaved draft even when called directly',async()=>{const f=fixture();f.ctx.publishBoBot=async()=>assert.fail('unsaved publish');await f.run('publish');});
