import {test} from 'node:test';import assert from 'node:assert/strict';
import {buildBotDelta,rebaseBotDraft} from '../src/lib/bot-delta.ts';
const base={name:'bot',description:'desc',content:{steps:[{id:'s1',kind:'check',action:'old'},{id:'s2',kind:'check'},{id:'s3',kind:'check'}],capability_refs:['a','b'],policy_refs:['p'],trigger:{mode:'manual',enabled:true}}};
test('one step edited sends only touched fields and retains other IDs',()=>{const draft=structuredClone(base);draft.content.steps[0].action='edit';assert.deepEqual(buildBotDelta(base,draft,4),{expected_version:4,content:{steps:[{id:'s1',action:'edit'}]}});});
test('omitted steps preserve; removal from full editor produces explicit op',()=>{assert.deepEqual(buildBotDelta(base,{...base,content:{}},4),{expected_version:4});const d=structuredClone(base);d.content.steps=d.content.steps.slice(0,2);assert.deepEqual(buildBotDelta(base,d,4),{expected_version:4,steps_remove:['s3']});});
test('addition, reference removals and description delta are explicit',()=>{const d=structuredClone(base);d.description='changed';d.content.steps.push({id:'s4',kind:'check'});d.content.capability_refs=['b','c'];assert.deepEqual(buildBotDelta(base,d,4),{expected_version:4,description:'changed',content:{steps:[{id:'s4',kind:'check'}],capability_refs:['c']},capability_refs_remove:['a']});});
test('rebase preserves concurrent addition and independent metadata/step edit',()=>{const d=structuredClone(base);d.content.steps[0].action='draft';d.content.steps=d.content.steps.slice(0,2);const fresh=structuredClone(base);fresh.name='remote';fresh.content.steps[0].kind='remote';fresh.content.steps.push({id:'s4',kind:'new'});const end=rebaseBotDraft(base,d,fresh);assert.equal(end.name,'remote');assert.deepEqual(end.content.steps,[{id:'s1',kind:'remote',action:'draft'},base.content.steps[1],{id:'s4',kind:'new'}]);});
test('refetch does not guess vminus1; arbitrary old version remains unchanged in payload',()=>{assert.equal(buildBotDelta(base,{...base,name:'edit'},1).expected_version,1);});
test('remote deletion and duplicate new ID cannot be silently recreated',()=>{const d=structuredClone(base);d.content.steps[0].action='draft';const f=structuredClone(base);f.content.steps.shift();assert.throws(()=>rebaseBotDraft(base,d,f));d.content.steps.push({id:'s4',kind:'a'});f.content.steps=structuredClone(base.content.steps);f.content.steps.push({id:'s4',kind:'b'});assert.throws(()=>rebaseBotDraft(base,d,f));});
test('invalid duplicate steps refused before request',()=>{const d=structuredClone(base);d.content.steps.push(d.content.steps[0]);assert.throws(()=>buildBotDelta(base,d,4));});

test('unsupported nested list removal refuses before a fictitious save',()=>{const b={...base,content:{...base.content,trigger:{tags:['a','b']}}};const d={...b,content:{...b.content,trigger:{tags:['a']}}};assert.throws(()=>buildBotDelta(b,d,2));});
