// Unit-test the actual page handler bodies and actual bot reload callback.
// This is neither mounted React nor headless/API integration; no screenshots.
import {test} from 'node:test';import assert from 'node:assert/strict';
import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {fileURLToPath,pathToFileURL} from 'node:url';
const require=createRequire(import.meta.url),ts=require(process.env.BO_UI_TYPESCRIPT||'typescript');
const source=process.env.BO_UI_SOURCE_DIR||path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../src');
const {BoApiError}=await import(pathToFileURL(path.join(source,'lib/bo.ts')));
function handler(file,name,ctx){const sf=ts.createSourceFile(file,fs.readFileSync(path.join(source,file),'utf8'),ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let body;function visit(n){if(ts.isFunctionDeclaration(n)&&n.name?.text===name)body=n.getText(sf);if(ts.isVariableDeclaration(n)&&n.name.getText(sf)===name&&ts.isCallExpression(n.initializer))body=n.initializer.arguments[0].getText(sf);ts.forEachChild(n,visit)}visit(sf);assert(body,`handler absent ${name}`);const js=ts.transpileModule('const fn = '+body+';', {compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;return Function(...Object.keys(ctx),js+'return fn;')(...Object.values(ctx));}
import {PersonUpdateError} from '../src/lib/api.ts';
import {personPatch} from '../src/lib/person-edit.ts';
import {settingPatch,CSV_SETTINGS,catalogPatch,P0EditError} from '../src/lib/p0-edit.ts';
import {buildBotDelta} from '../src/lib/bot-delta.ts';
const conflict=()=>Promise.reject(new BoApiError(409,'version_conflict'));
test('Settings409 keeps draft and reports conflict',async()=>{let notices=[],saved=0;const draft='unu,doi,trei,patru';const ctx={draft,base:{value:'unu,doi,trei',version:2},removeDraft:'',settingPatch,CSV_SETTINGS,P0EditError,setBase:()=>{},setDraft:()=>{},setRemoveDraft:()=>{},setConflict:()=>{},setting:{type:'text',key:'bo.router.allowed_providers',version:2},setSaving:()=>{},setNotice:x=>notices.push(x),putBoSetting:conflict,onSaved:()=>saved++,BoApiError};await handler('app/settings/bo/page.tsx','save',ctx)();assert.equal(ctx.draft,draft);assert.equal(saved,0);assert.equal(notices.at(-1).kind,'warn');});
test('bot409 must preserve typed draft despite fresh remote revision',async()=>{const local={name:'typed name',description:'typed description',contentJson:'{"steps":[{"id":"s4"}]}'};const before=structuredClone(local);const ctx={buildBotDelta,editBase:{current:{name:'base',description:'base',content:{steps:[{id:'s1'},{id:'s2'},{id:'s3'}]}}},...local,id:'synthetic',state:{kind:'data',detail:{bot:{draft_version:2}}},setBusy:()=>{},setNotice:()=>{},BoApiError,patchBoBot:conflict,load:null,getBoBot:async()=>({bot:{name:'remote name',description:'remote description'},draft:{content:{steps:[{id:'s1'}]}}}),listBoRuns:async()=>({runs:[]}),getBoSettings:async()=>({role:'admin'}),setState:()=>{},setName:x=>local.name=x,setDescription:x=>local.description=x,setContentJson:x=>local.contentJson=x};ctx.load=handler('app/bo/bots/[id]/page.tsx','load',ctx);await handler('app/bo/bots/[id]/page.tsx','saveDraft',ctx)();assert.deepEqual(local,before);});
test('profile card409 keeps editor open and reports failure',async()=>{let editing=true,error=null;const ctx={onSave:conflict,setEditing:x=>editing=x,setError:x=>error=x};await handler('components/company-profile/ProfileSections.tsx','handleSave',ctx)();assert.equal(editing,true);assert.match(error,/failed/i);});
test('People409 does not close/reset edit form; real CAS delta and typed conflict',async()=>{let editing=true,saved=false,error=null,conflicted=false;const form={full_name:'Typed Name',role:'viewer',email:'typed@bo01.invalid',slack_user_id:'',telegram_chat_id:'',discord_user_id:'',preferred_channel:'any',response_sla_hours:'24',on_leave_until:'',authority_scope:[],availability:[]};const original=structuredClone(form);const person={id:1,version:7,full_name:'Base Name',role:'viewer',email:'typed@bo01.invalid',slack_user_id:null,telegram_chat_id:null,discord_user_id:null,preferred_channel:'any',response_sla_hours:24,on_leave_until:null,authority_scope:[],availability:[]};const ctx={form,person,conflict:false,personPatch,PersonUpdateError,personId:1,setConflict:x=>conflicted=x,setSaveErr:x=>error=x,setSaving:()=>{},updatePerson:async(id,patch)=>{assert.equal(id,1);assert.deepEqual(patch,{expected_version:7,full_name:'Typed Name'});throw new PersonUpdateError(409)},setPerson:()=>assert.fail('unexpected successful readback'),setEditing:x=>editing=x,setSaved:x=>saved=x};await handler('app/people/[id]/page.tsx','save',ctx)();assert.deepEqual(form,original);assert.equal(editing,true);assert.equal(saved,false);assert.equal(conflicted,true);assert.match(error,/409/);});
test('catalog409 keeps dialog fields and does not call success close',async()=>{let close=0,error=null,conflicted=false;const fields=Object.fromEntries(['score','taskKind','methodology','evalRef','evalVersion','observedAt','sampleCount','modelVersion','validUntil'].map(k=>[k,'']));Object.assign(fields,{provider:'synthetic',modelId:'model',state:'ACTIVE',capabilities:'unu,doi,trei,patru',regions:'eu,us',costIn:'1.00',costOut:'2.00',currency:'EUR',purpose:'typed',source:'admin'});const original=structuredClone(fields);const entry={entry_id:'entry',version:2,provider:'synthetic',model_id:'model',purpose:'base',source:'admin'};const ctx={...fields,entry,base:entry,conflict:false,removeCaps:'',removeRegions:'',catalogPatch,initialObservedAt:{current:'2026-10-05T00:00:00Z'},originalPayload:{current:{}},csv:s=>s.split(',').filter(Boolean),parseMoneyInput:s=>s,setErr:x=>error=x,setConflict:x=>conflicted=x,setBusy:()=>{},updateBoCatalogEntry:conflict,createBoCatalogEntry:()=>assert.fail('unexpected create'),onSaved:()=>close++,BoApiError};ctx.payload=handler('app/bo/routing/page.tsx','payload',ctx);ctx.originalPayload.current=ctx.payload();await handler('app/bo/routing/page.tsx','submit',ctx)();assert.deepEqual(fields,original);assert.equal(close,0);assert.equal(conflicted,true);assert.match(error,/Altă sesiune/);});
import {uploadDocument} from '../src/lib/api.ts';
test('document403 keeps real selected File/domain and retry draft; actual transport has status',async()=>{const originalFetch=global.fetch;const file=new File(['synthetic'],'fixture.txt',{type:'text/plain'});let pending=null,error=null,isUploading=false,docs=0;const input={value:'selected-fixture.txt'};try{global.fetch=async()=>({ok:false,status:403});const ctx={fileInputRef:{current:input},domain:'general',setPendingFile:x=>pending=x,setIsUploading:x=>isUploading=x,setError:x=>error=x,uploadDocument,listDocuments:async()=>{docs++;return[]},setDocs:()=>{}};await handler('components/knowledge/CompanyPanel.tsx','handleFile',ctx)(file);assert.equal(pending,file);assert.equal(input.value,'selected-fixture.txt');assert.equal(ctx.domain,'general');assert.equal(isUploading,false);assert.equal(docs,0);assert.match(error,/HTTP 403/);global.fetch=async()=>({ok:true,status:200,json:async()=>({filename:'fixture.txt'})});await handler('components/knowledge/CompanyPanel.tsx','handleFile',ctx)(file);assert.equal(pending,null);assert.equal(input.value,'');assert.equal(docs,1);}finally{global.fetch=originalFetch}});
