import {test} from 'node:test';import assert from 'node:assert/strict';
import {personEdit,personPatch,rebasePersonEdit} from '../src/lib/person-edit.ts';
const base=()=>({id:1,version:10,full_name:'Original',role:'viewer',email:'person@example.invalid',slack_user_id:null,telegram_chat_id:null,discord_user_id:null,preferred_channel:'any',response_sla_hours:24,on_leave_until:'2026-11-01',authority_scope:['one'],availability:[],department_slugs:['one','two','three'],is_principal:false,archived:false,reports_to_person_id:null});
test('untouched fields and department collections omitted; real read CAS',()=>{const b=base(),f=personEdit(b);f.full_name='Edited';assert.deepEqual(personPatch(f,b),{expected_version:10,full_name:'Edited'});});
test('20→10 explicit intended revert remains a delta',()=>{const b={...base(),response_sla_hours:20},f=personEdit(b);f.response_sla_hours='10';assert.deepEqual(personPatch(f,b),{expected_version:10,response_sla_hours:10});});
test('true base v−3 retained, never assumes v−1',()=>{const b=base(),f=personEdit(b);f.role='editor';assert.equal(personPatch(f,b).expected_version,10);const fresh={...b,version:13,full_name:'Other',department_slugs:['one','three','four']};const rebase=rebasePersonEdit(f,b,fresh);assert.equal(rebase.full_name,'Other');assert.equal(rebase.role,'editor');assert.deepEqual(personPatch(rebase,fresh),{expected_version:13,role:'editor'});assert.deepEqual(fresh.department_slugs,['one','three','four']);});
test('empty untouched arrays omitted; explicit availability remove serialized',()=>{const b=base(),f=personEdit(b);f.full_name='Edited';assert(!('availability' in personPatch(f,b)));const windows={...b,availability:[{weekdays:[1],start_local:'09:00',end_local:'17:00',timezone:'UTC'}]};const edited=personEdit(windows);edited.availability=[];assert.deepEqual(personPatch(edited,windows),{expected_version:10,availability:[]});});
test('clear date uses explicit supported clear_on_leave',()=>{const b=base(),f=personEdit(b);f.on_leave_until='';assert.deepEqual(personPatch(f,b),{expected_version:10,clear_on_leave:true});});
test('unchanged and missing version fail closed; malformed SLA refused',()=>{const b=base(),f=personEdit(b);assert.throws(()=>personPatch(f,b),/Nicio/);f.full_name='Edited';for(const v of [undefined,0,-1,1.5])assert.throws(()=>personPatch(f,{...b,version:v}),/Versiunea/);f.response_sla_hours='bad';assert.throws(()=>personPatch(f,b),/SLA/);});
test('rebase preserves draft and adopts untouched concurrent fields, no mutation',()=>{const b=base(),f=personEdit(b);f.full_name='My Draft';const fresh={...b,version:11,role:'Concurrent',availability:[{weekdays:[2],start_local:'10:00',end_local:'11:00',timezone:'UTC'}]};const rebase=rebasePersonEdit(f,b,fresh);assert.equal(f.role,'viewer');assert.equal(rebase.role,'Concurrent');assert.equal(rebase.full_name,'My Draft');assert.deepEqual(personPatch(rebase,fresh),{expected_version:11,full_name:'My Draft'});});
test('single authority selection remains explicit; unrelated roster untouched',()=>{const b=base(),f=personEdit(b);f.authority_scope=['one','two'];assert.deepEqual(personPatch(f,b),{expected_version:10,authority_scope:['one','two']});});

test('unsupported contact clear fails explicitly, never reports saved null',()=>{const b=base(),f=personEdit(b);f.email='';assert.throws(()=>personPatch(f,b),/nu este suportată/);assert.equal(b.email,'person@example.invalid');assert.equal(f.email,'');});
